server:
  port: 8006

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : http://127.0.0.1:8761/eureka

spring:
  application:
    name: management
  kafka:
    producer:
      bootstrap-servers: cheeseballoon.site:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer